### ISSUE TITLE
Windows platform support

### ISSUE THREAD

**Issue by sneurlax** [cypherstack/flutter_libmonero#61]
Latest Windows platform support work is being done on the [`win`](https://github.com/cypherstack/flutter_libmonero/tree/win) branch.  Latest error is:

```
2024-01-31 20:00:42,429	T wallet_path: C:\Users\user\AppData\Roaming/stackwallet/wallets/monero/689b3c00-c073-11ee-8be5-1defb6319882/689b3c00-c073-11ee-8be5-1defb6319882
2024-01-31 20:00:42,429	T keys_file_exists: false  wallet_file_exists: false
2024-01-31 20:00:42,429	T refreshThreadFunc: starting refresh thread
2024-01-31 20:00:42,429	T refreshThreadFunc: waiting for refresh...
2024-01-31 20:00:42,445	I caching ringdb key
2024-01-31 20:00:42,459	D Calculated blockchain height: 3076348
2024-01-31 20:00:42,459	D Reconnecting...
2024-01-31 20:00:42,459	D Some problems at connect, message: resolve: No such host is known [system:11001]
2024-01-31 20:00:42,459	D Failed to connect to :
2024-01-31 20:00:42,459	I Failed to invoke http request to  /json_rpc
2024-01-31 20:00:42,459	E Failed to connect to daemon
2024-01-31 20:00:42,459	D Reconnecting...
2024-01-31 20:00:42,459	D Some problems at connect, message: resolve: No such host is known [system:11001]
2024-01-31 20:00:42,459	D Failed to connect to :
2024-01-31 20:00:42,459	I Failed to invoke http request to  /json_rpc
2024-01-31 20:00:42,459	E Failed to connect to daemon
2024-01-31 20:00:42,486	D C:\Users\user\AppData\Roaming/stackwallet/wallets/monero/689b3c00-c073-11ee-8be5-1defb6319882/689b3c00-c073-11ee-8be5-1defb6319882.keys is already unlocked.
flutter: Invalid argument(s): Failed to lookup symbol 'account_refresh': error code 127
flutter: MoneroWalletsManager Error: Invalid argument(s): Failed to lookup symbol 'account_refresh': error code 127
flutter: Log: [Fatal][2024-01-31 20:00:42.837Z]: Invalid argument(s): Failed to lookup symbol 'account_refresh': error code 127
flutter: #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
flutter: #1      accountRefreshNative (package:cw_monero/api/account_list.dart:16:6)
flutter: #2      accountRefreshNative (package:cw_monero/api/account_list.dart)
flutter: #3      refreshAccounts (package:cw_monero/api/account_list.dart:36:5)
flutter: #4      MoneroAccountListBase.refresh (package:cw_monero/monero_account_list.dart:70:20)
flutter: #5      new MoneroAccountListBase (package:cw_monero/monero_account_list.dart:14:5)
flutter: #6      new MoneroAccountList (package:cw_monero/monero_account_list.dart)
flutter: #7      new MoneroWalletAddressesBase (package:cw_monero/monero_wallet_addresses.dart:16:19)
flutter: #8      new MoneroWalletAddresses (package:cw_monero/monero_wallet_addresses.dart)
flutter: #9      new MoneroWalletBase (package:cw_monero/monero_wallet.dart:49:23)
flutter: #10     new MoneroWallet (package:cw_monero/monero_wallet.dart)
flutter: #11     MoneroWalletService.create (p
flutter: ackage:cw_monero/monero_wallet_service.dart:76:22)
flutter: <asynchronous suspension>
flutter: #12     WalletCreationService.create (package:flutter_libmonero/core/wallet_creation_service.dart:33:12)
flutter: <asynchronous suspension>
flutter: #13     MoneroWallet.init (package:stackwallet/wallets/wallet/impl/monero_wallet.dart:334:24)
flutter: <asynchronous suspension>
flutter: #14     _NewWalletRecoveryPhraseWarningViewState.build.<anonymous closure>.<anonymous closure> (package:stackwallet/pages/add_wallet_views/new_wallet_recovery_phrase_warning_view/new_wallet_recovery_phrase_warning_view.dart:616:45)
flutter: <asynchronous suspension>
flutter: 
flutter: Log: [Fatal][2024-01-31 20:00:42.851Z]: mnemonic has not been set
flutter: #0      MnemonicInterface.getMnemonic (package:stackwallet/wallets/wallet/wallet_mixin_interfaces/mnemonic_interface.dart:12:7)
flutter: <asynchronous suspension>
flutter: #1      MnemonicInterface.getMnemonicAsWords (package:stackwallet/wallets/wallet/wallet_mixin_interfaces/mnemonic_interface.dart:19:22)
flutter: <asynchronous suspension>
flutter: #2      _NewWalletRecoveryPhraseWarningViewState.build.<anonymous closure>.<anonymous closure> (package:stackwallet/pages/add_wallet_views/new_wallet_recovery_phrase_warning_view/new_wallet_recovery_phrase_warning_view.dart:635:51)
flutter: <asynchronous suspension>
flutter: 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: mnemonic has not been set
#0      MnemonicInterface.getMnemonic (package:stackwallet/wallets/wallet/wallet_mixin_interfaces/mnemonic_interface.dart:12:7)
<asynchronous suspension>
#1      MnemonicInterface.getMnemonicAsWords (package:stackwallet/wallets/wallet/wallet_mixin_interfaces/mnemonic_interface.dart:19:22)
<asynchronous suspension>
#2      _NewWalletRecoveryPhraseWarningViewState.build.<anonymous closure>.<anonymous closure> (package:stackwallet/pages/add_wallet_views/new_wallet_recovery_phrase_warning_view/new_wallet_recovery_phrase_warning_view.dart:635:51)
<asynchronous suspension>

flutter: didChangeAppLifecycleState: inactive
```

This issue (Failed to lookup symbol 'account_refresh': error code 127) should have been resolved by one of the latest commits on `win` ([this](https://github.com/cypherstack/flutter_libmonero/commit/91bf895617c24ee50348d9dfa1ffff45e754a15a) or [this](https://github.com/cypherstack/flutter_libmonero/commit/552b5a7eef40f0040772ca2789dfca886b9d1f3a)), but it persists despite `account_refresh` being annotated in the same way as other functions.

**Comment by sneurlax** [comment]
This has worked for a long time.
